---
- name: testing playbook with vault
  hosts: all
  become: true
  tasks:
    - name: cloan a repository
      git:
        repo: https://github.com/ebobant/aws_test.git
        dest: /opt/ansible/
        accept_hostkey: yes
