---
- name: this playbook insatll packages
  hosts: webservers
  # become: true
  tasks:
  - name: install package
    yum:
      name: ['git', 'wget', 'telnet', 'gzip', 'make']
      state: installed 
